### ISSUE TITLE
Exceeding disk_space not handled gracefully

### ISSUE THREAD

**Issue by arweave-kyle** [ArweaveTeam/arweave#34]
A few users have reported errors when using the `disk_space` option to limit the amount of disk space used by the node, it doesn't appear to handle this limit gracefully, and can in some instances cause a node to not join as it doesn't reserve/clear enough space to download the current tail on join.

Example log
```
=INFO REPORT==== 30-Jul-2018::02:39:08 ===
    'NodeERROR': {{badrecord,block},
                  [{ar_node,server,1,[{file,"src/ar_node.erl"},{line,1115}]},
                   {ar_node,server,1,[{file,"src/ar_node.erl"},{line,965}]},
                   {ar_node,server,1,[{file,"src/ar_node.erl"},{line,968}]},
                   {ar_node,server,1,[{file,"src/ar_node.erl"},{line,1026}]},
                   {ar_node,server,1,[{file,"src/ar_node.erl"},{line,968}]},
                   {ar_node,server,1,[{file,"src/ar_node.erl"},{line,818}]},
                   {ar_node,server,1,[{file,"src/ar_node.erl"},{line,965}]},
                   {ar_node,server,1,[{file,"src/ar_node.erl"},{line,968}]}]}

=INFO REPORT==== 30-Jul-2018::02:39:08 ===
    node_not_joining
    reason: cannot_get_full_block_from_peer
    received_instead: unavailable

=INFO REPORT==== 30-Jul-2018::02:39:33 ===
    writing_block_to_disk: <<"eK7WmQC5H-jsDayVIQ7I0HtwSYTLJ6_S6U-pUW-Qc7BDuMA1_5CevwCbv5EfrUxi">>

=INFO REPORT==== 30-Jul-2018::02:39:34 ===
    {not_enough_space_to_write_block}
    {block_not_written}
```

**Comment by samcamwilliams** [comment]
Fixed in the fix for #36 .

**Comment by 2072** [comment]
Actually it's still not fixed, I have set it at 32 and it crashes a few minutes after joining:

```
=INFO REPORT==== 25-Dec-2018::21:19:13 ===
    writing_block: 108516
    writing_recall_block: 74193
    blocks_written: 100
    blocks_to_write: 0

=INFO REPORT==== 25-Dec-2018::21:19:15 ===
    writing_block_to_disk: <<"tiIoiEW0782SDcQ4gKIdEOqvoBWkkyTOpJn-f1_qDbwxSrzNNHug2VRelRqeSQkO">>

=INFO REPORT==== 25-Dec-2018::21:19:15 ===
    {not_enough_space_to_write_block}
    {block_not_written}

=INFO REPORT==== 25-Dec-2018::21:19:28 ===
    'NodeWorkerERROR': {{badrecord,block},
                        [{ar_node_worker,recovered_from_fork,2,
                             [{file,"src/ar_node_worker.erl"},{line,606}]},
                         {ar_node_worker,handle,2,
                             [{file,"src/ar_node_worker.erl"},{line,129}]},
                         {ar_node_worker,server,2,
                             [{file,"src/ar_node_worker.erl"},{line,56}]}]}
```

my node info ends up being this:

```json
{"network":"arweave.N.1","version":5,"release":19,"height":-1,"current":"not_joined","blocks":104750,"peers":57,"queue_length":0,"node_state_latency":24}
```
